### PR TITLE
Automatically load the acpi_call module if needed

### PR DESCRIPTION
**Pull request by bjornfor**
The script already runs as root, so we can load the module if needed,
instead of making the user do it.

Arguably the user can configure the module to be loaded at boot, but
since this tool doesn't _necessarily_ get run that frequently, I figured
"lazy loading" the acpi_call module is a good idea.

### CODE REVIEW

**Comment by bjornfor** [comment]
Btw, thanks for writing this tool!

**Comment by shaansubbaiah** [comment]
Thanks! Glad to find other people using it. 

This is my first complete shell program so I'm not completely sure how the change loads the `acpi_call` module?

I'm not sure how these lines loads acpi, instead of just checking if it is loaded?
```bash
if ! modprobe acpi_call; then
    echo "Error: acpi_call module could not be loaded!" >&2
    exit 1
fi
```

**Comment by bjornfor** [comment]
I'm not sure I understand the question... `modprobe acpi_call` loads the module and the `if` checks the exit status. If exit status is non-zero (`modprobe` failed) we get the error message and the script exits. If no error, we know the module is loaded and the script skips over the `if`-body and keeps running.

Btw, I realized that checking if the module is loaded first is unneeded as `modprobe` does that itself (and does it faster), so I pushed an update to fix that.

**Comment by shaansubbaiah** [comment]
Your comment resolved my confusion. Merging :)

**Comment by bjornfor** [comment]
Thanks!

**Pull request merged**
